apiVersion: v1
kind: Service
metadata:
  name: app-three
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: app-three

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-three
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app-three
    spec:
      restartPolicy: Always
      containers:
      - name: app-three
        image: paulbouwer/hello-kubernetes:1.10
        ports:
        - containerPort: 8080
        env:
          - name: MESSAGE
            value: "Hello from app3."

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-three
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-three
            port:
              number: 80