Vagrant.configure("2") do |config|
    DISTRO = "debian/bookworm64"
    USER_NAME = "vvarussa"
    CPU_COUNT = 1
    MEMORY_MB = 1024
    SERVER_IP = "192.168.56.110"
    SERVER_WORKER_IP = "192.168.56.111"
  
    # Como usamos virtualbox, devemos seguir a doc dela https://developer.hashicorp.com/vagrant/docs/providers/virtualbox
    config.vm.provider "virtualbox" do |v|
      v.memory = MEMORY_MB
      v.cpus = CPU_COUNT
    end
  
    config.vm.box = DISTRO
  
    config.vm.define "#{USER_NAME}S" do |server|
      server.vm.hostname = "#{USER_NAME}S"
  
      server.vm.network "private_network", ip: SERVER_IP
      server.vm.provision "file", source: "./confs", destination: "$HOME/confs"
      server.vm.provision "shell", path: "scripts/install_config_server.sh"
    end

    config.vm.define "#{USER_NAME}SW" do |serverWorker|
        serverWorker.vm.hostname = "#{USER_NAME}SW"

        serverWorker.vm.network "private_network", ip: SERVER_WORKER_IP
        serverWorker.vm.provision "shell", path: "scripts/install_config_worker.sh"
    end
end